#!/usr/bin/env bash
#
# Produce a machine-generated record of a verification run.
#
# `spec/06-testing.md` used to transcribe test counts by hand, which drifted:
# it claimed 1,154 functional tests while the suite actually ran 1,163. This
# script writes the counts, the commit they came from, and the environment they
# ran in, so the document can point at evidence instead of restating it.
#
# Usage: bash scripts/verification-summary.sh [output-path]
# Default output: report/verification-summary.md

set -euo pipefail

output=${1:-report/verification-summary.md}
tmp_dir=$(mktemp -d)
trap 'rm -rf "$tmp_dir"' EXIT

mkdir -p "$(dirname "$output")"

# Count tests from vitest's JSON reporter rather than scraping human output.
run_suite() {
  local label=$1
  local json=$2
  shift 2
  if ! "$@" --reporter=json --outputFile="$json" >"$tmp_dir/$label.log" 2>&1; then
    echo "  (suite reported failures — see $tmp_dir/$label.log)" >&2
  fi
}

summarize() {
  local json=$1
  if [[ ! -f $json ]]; then
    echo "unavailable"
    return
  fi
  node -e '
    const report = require(process.argv[1]);
    const files = report.testResults?.length ?? report.numTotalTestSuites ?? 0;
    const passed = report.numPassedTests ?? 0;
    const failed = report.numFailedTests ?? 0;
    const total = report.numTotalTests ?? passed + failed;
    process.stdout.write(`${files} files, ${passed}/${total} passed` + (failed ? `, ${failed} FAILED` : ""));
  ' "$json"
}

echo "Running functional suite..." >&2
run_suite functional "$tmp_dir/functional.json" npx vitest run

echo "Running performance suite..." >&2
run_suite perf "$tmp_dir/perf.json" npx vitest run --config vitest.perf.config.ts

commit=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
commit_short=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
dirty=""
if ! git diff --quiet 2>/dev/null || ! git diff --cached --quiet 2>/dev/null; then
  dirty=" (working tree modified)"
fi

{
  echo "# Verification Summary"
  echo
  echo "Generated by \`scripts/verification-summary.sh\`. Do not edit by hand."
  echo
  echo "| Field | Value |"
  echo "| --- | --- |"
  echo "| Generated | $(date -u +"%Y-%m-%dT%H:%M:%SZ") |"
  echo "| Commit | \`$commit_short\` ($commit)$dirty |"
  echo "| Node | $(node --version) |"
  echo "| Platform | $(uname -s) $(uname -m) |"
  echo "| Functional (\`pnpm test\`) | $(summarize "$tmp_dir/functional.json") |"
  echo "| Performance (\`pnpm test:perf\`) | $(summarize "$tmp_dir/perf.json") |"
} >"$output"

echo "Wrote $output" >&2
cat "$output"
